apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lumbago-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: lumbago.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lumbago-frontend
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: lumbago-backend
                port:
                  number: 8000
